-- ZeroHunger Supabase Database Schema

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id bigint generated by default as identity primary key,
    username text unique,
    password text,
    role text,
    name text,
    email text,
    emoji text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Donations Table
CREATE TABLE IF NOT EXISTS public.donations (
    id bigint generated by default as identity primary key,
    donor_username text,
    donor_name text,
    food_name text,
    food_type text,
    quantity integer,
    location_label text,
    lat numeric,
    lng numeric,
    mfg_date text,
    expiry_date text,
    freshness_score integer default 10,
    pay_type text default 'free',
    status text default 'available',
    claimed_by text,
    volunteer_name text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Requests Table
CREATE TABLE IF NOT EXISTS public.requests (
    id bigint generated by default as identity primary key,
    req_username text,
    req_name text,
    food_name text,
    quantity integer,
    urgency text,
    location_label text,
    status text default 'pending',
    needs_volunteer boolean default false,
    priority_score integer default 0,
    req_type text default 'standard',
    donation_id bigint references public.donations(id) on delete set null,
    assigned_to text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Trusts Verification Table
CREATE TABLE IF NOT EXISTS public.trusts (
    id bigint generated by default as identity primary key,
    trust_username text,
    trust_name text,
    reg_number text,
    verification_status text default 'pending',
    cert_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Trust Fund Requests Table
CREATE TABLE IF NOT EXISTS public.fund_requests (
    id bigint generated by default as identity primary key,
    trust_username text,
    trust_name text,
    purpose text,
    amount numeric,
    upi_id text,
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Mass Event Donations Table
CREATE TABLE IF NOT EXISTS public.mass_donations (
    id bigint generated by default as identity primary key,
    place text,
    event_time text,
    organiser text,
    phone_number text,
    is_phone_verified boolean default false,
    event_photo_url text,
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint generated by default as identity primary key,
    message text,
    urgency text,
    user_id text,
    read_receipt boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Messages (P2P Chat) Table
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint generated by default as identity primary key,
    sender_username text,
    receiver_username text,
    message_text text,
    context_type text default 'chat',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Volunteers Table
CREATE TABLE IF NOT EXISTS public.volunteers (
    id bigint generated by default as identity primary key,
    name text,
    username text,
    vehicle text,
    status text default 'active',
    assigned_req integer default 0,
    score integer default 0,
    badges text[],
    pickup_lat numeric,
    pickup_lng numeric,
    pickup_location text,
    shift text,
    time_slot text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Ratings Table
CREATE TABLE IF NOT EXISTS public.ratings (
    id bigint generated by default as identity primary key,
    target_username text,
    category text,
    score integer,
    review text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);