-- ZeroHunger Supabase Database Schema

-- 1. Donations Table
CREATE TABLE IF NOT EXISTS public.donations (
    id bigint generated by default as identity primary key,
    donor_username text,
    donor_name text,
    food_name text,
    food_type text,
    quantity integer,
    location_label text,
    lat numeric,
    lng numeric,
    mfg_date text,
    expiry_date text,
    freshness_score integer default 10,
    pay_type text default 'free',
    status text default 'available',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Requests Table
CREATE TABLE IF NOT EXISTS public.requests (
    id bigint generated by default as identity primary key,
    req_username text,
    req_name text,
    food_name text,
    quantity integer,
    urgency text,
    location_label text,
    status text default 'pending',
    needs_volunteer boolean default false,
    priority_score integer default 0,
    req_type text default 'standard',
    donation_id bigint references public.donations(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Trusts Verification Table
CREATE TABLE IF NOT EXISTS public.trusts (
    id bigint generated by default as identity primary key,
    trust_username text,
    trust_name text,
    reg_number text,
    verification_status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Trust Fund Requests Table
CREATE TABLE IF NOT EXISTS public.fund_requests (
    id bigint generated by default as identity primary key,
    trust_username text,
    trust_name text,
    purpose text,
    amount numeric,
    upi_id text,
    status text default 'open',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Mass Event Donations Table
CREATE TABLE IF NOT EXISTS public.mass_donations (
    id bigint generated by default as identity primary key,
    place text,
    event_time text,
    organiser text,
    phone_number text,
    is_phone_verified boolean default false,
    event_photo_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optional: Enable Row Level Security (RLS) if you want to secure tables
-- ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.trusts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.fund_requests ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.mass_donations ENABLE ROW LEVEL SECURITY;

-- Note: To keep things simple for the P2P app MVP, you can disable RLS or allow open policies.
-- Create an open policy for donations (example)
-- CREATE POLICY "Allow all operations" ON public.donations FOR ALL USING (true);